### ISSUE TITLE
README.md typo?

### ISSUE THREAD

**Issue by Symbolics** [tfeb/conduit-packages#1]
Should:

> Or perhaps I _only_ want to burn petrol:
> ```
> (defpackage :com.cley.my-great-prog
>   (:use)
>   (:extends/excluding :com.cley.my-great-prog.clever-hacks
>    #:burn-petrol)
>  ...)
> ```

actually be:
(:extends/_including_ ...)

**Comment by tfeb** [comment]
Yes, it should!  I'll fix it: thank you for actually reading it!

**Comment by tfeb** [comment]
Resolved by 438b1c2b7cb6d015a0cca4c8228734ddc09f5af2.

Thanks again

**Comment by Symbolics** [comment]
A bit off topic, but I thought you might be worth asking, as your name seems familiar from before comp.lang.lisp became all spam: are you the one that wrote a common lisp patch facility? I know I saw someone reference one at some point long ago, but I can't find anything for patching out there at the moment.

**Comment by tfeb** [comment]
Yes, that was probably me.  I don't remember how it worked in detail but it was probably based on the Symbolics one (heh...).  I don't think it did anything very magic.  I have some distant intention to revive & publish some of that code (I've been putting it off because it's not that small and it's all sitting in CVS in some dump so I need to drag it all into git before even starting).  My email address hasn't changed since the days of CLL though, so if you can find those old messages you can probably find me & I'll let you know if I make any progress.
