### ISSUE TITLE
Using `conduit-package` in a project

### ISSUE THREAD

**Issue by lsp-ableton** [tfeb/conduit-packages#3]
Thanks for your work on this package- it seems like a promising idea. Unfortunately, I'm struggling to get it set up with my (asdf) project to set up in a way that makes sense. I end up with this code sitting in the file which I know to be the first one that will compile:
```
(eval-when
    (:compile-toplevel :load-toplevel :execute)
  (in-package :cl-user)
  (use-package :org.tfeb.conduit-packages/define-package))
```

By now, `sbcl` seems to define `define-package` as a built-in (or is it just part of asdf?), so I also get naming conflicts whenever I start my project. Any ideas about how to structure the project so that, e.g. (ql:quickload "my-project") will result in `define-package` being defined for all the packages in the system?

**Comment by tfeb** [comment]
Hello, sorry for the belated reply.  I've got a foul cold but I will get back to this with something (I hope) helpful in a day or so.

**Comment by tfeb** [comment]
Hi, the trick is generally to define a sane package in which you can then use `define-package`.  You can't trust `CL-USER` to be 'sane' in that sense, because it's allowed to be filled with all sorts of stuff.  So, for instance the file where you define packages might look like (you must explicitly say `(:use ...)` as the defaults can be wrong).

```
(org.tfeb.conduit-packages/define-package:define-package :my-system/pkg
  (:use :cl :org.tfeb.conduit-packages/define-package))

(in-package :my-system/pkg)

(define-package :my-system
  ...)
```

If you look at [Štar's package file](https://github.com/tfeb/star/blob/main/pkg.lisp) it looks pretty much like this.

**Comment by lane-s** [comment]
I see. That makes sense- thanks!
